# User and blog data
baseurl: "/dragon-theme"
url: "https://mhernandes.github.io"
title: Dragon Theme
description: >
  Dragon theme
email: user@mail.com
facebook: lorem
instagram: lorem
twitter: lorem
github: lorem
spotify: lorem

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

series:
    - title: title

site_links:
    - title: home
      url: /
      icon: home 
      
    - title: blog
      url: /blog
      icon: blog
      
    - title: series
      url: /series
      icon: blog
      
    - title: categories
      url: /categories
      icon: blog
      
    - title: tags
      url: /tags
      icon: blog
      
    - title: about
      url: /about
      icon: info      

color: gray
lang: en

exclude: ['package.json', 'dev', 'node_modules', 'screenshots', 'gulpfile.js', 'back*.*', 'LICENSE.md', 'README.md']

sass:
  sass_dir: dev/scss

projects:
  - name: project.name
    slug: project-slug
    desc: 'project description'
    working: false # is this project in development?
    link: false # this project has a test-link or something like that?
    github: 'https://github.com/mhernandes/dragon-theme' # github repository